version: '3'
services:
  applicationserver:
    build: .
    hostname: applicationserver
    ports:
      - "8080:8080"
      - "8888:8888"
  db:
    image: mariadb:latest
    hostname: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  db_data: {}
